var data = [
  { id:"BlockStatement", selected: false },
  { id:"ExpressionStatement", selected: false},
  { id:"IfStatement", selected: false },
  { id:"LabeledStatement", selected: false },
  { id:"BreakStatement", selected: false },
  { id:"ContinueStatement", selected: false },
  { id:"WithStatement", selected: false },
  { id:"SwitchStatement", selected: false },
  { id:"ReturnStatement", selected: false },
  { id:"ThrowStatement", selected: false },
  { id:"TryStatement", selected: false },
  { id:"CatchClause", selected: false },
  { id:"WhileStatement", selected: false },
  { id:"DoWhileStatement", selected: false },
  { id:"ForStatement", selected: false },
  { id:"ForInStatement", selected: false },
  { id:"ForOfStatement", selected: false },
  { id:"LetStatement", selected: false },
  { id:"DebuggerStatement", selected: false },
  { id:"FunctionDeclaration", selected: false },
  { id:"VariableDeclaration", selected: false },
  { id:"VariableDeclarator", selected: false },
  { id:"ThisExpression", selected: false },
  { id:"ArrayExpression", selected: false },
  { id:"ObjectExpression", selected: false },
  { id:"FunctionExpression", selected: false },
  { id:"FunctionDeclaration", selected: false },
  { id:"BinaryExpression", selected: false },
  { id:"AssignmentExpression", selected: false },
  { id:"UpdateExpression", selected: false },
  { id:"LogicalExpression", selected: false },
  { id:"ConditionalExpression", selected: false },
  { id:"NewExpression", selected: false },
  { id:"SwitchCase" , selected: false }
];

module.exports= data;